### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by hi-one-gg** [ha4219/yolo-with-coral#1]
안녕하세요! 다름아니라 yolov7의 모델을 coral에서 사용하려고 하려는 중입니다.

@ha4219  님의 이 레포를 사용하면 정상적으로 coral용 tflite로 변환이 가능할까요?

**Comment by ha4219** [comment]
안녕하세요 @blackCmd 님!

한 3개월 전에 yolov7이 나오고 나서 이를 제가 진행하고 있는 연구에 적용시켜보고자 했었지만 최종적으로는 실패했습니다. (조금 더 찾아보면 될 것 같긴했는데 다른 프로젝트 참여로 인해 yolov5를 사용하고 있습니다)

제가 변경했던 방법은 torch -> onnx -> edgetpu, openvino -> edgetpu 이런식으로 변경했던 것 같은데 해당 결과는 아래와 같습니다.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/38957165/204962863-e1d3915e-52b6-4334-81bf-9a293e588309.png">

모델 변환까지만 완료하고 이후 코드를 확인하지 않아 내용은 부족하지만 충분히 찾아보면 가능할 것 같습니다.

그리고 위 에러는 저도 봤었는데 제가 스크립트로 따로 남겨놓지 않아서 정확히는 알려드릴 수 없지만 [edgetpu option](https://coral.ai/docs/edgetpu/compiler/#usage)을 확인하면 해결할 수 있을거라고 생각합니다.
```
Edge TPU Compiler version 16.0.384591198 Started a compilation timeout timer of 180 seconds. ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors. Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter. Compilation child process completed within timeout period. Compilation failed!
```

열공하세요!

**Comment by hi-one-gg** [comment]
> 안녕하세요 @blackCmd 님!
> 
> 한 3개월 전에 yolov7이 나오고 나서 이를 제가 진행하고 있는 연구에 적용시켜보고자 했었지만 최종적으로는 실패했습니다. (조금 더 찾아보면 될 것 같긴했는데 다른 프로젝트 참여로 인해 yolov5를 사용하고 있습니다)
> 
> 제가 변경했던 방법은 torch -> onnx -> edgetpu, openvino -> edgetpu 이런식으로 변경했던 것 같은데 해당 결과는 아래와 같습니다.
> 
> <img alt="image" width="393" src="https://user-images.githubusercontent.com/38957165/204962863-e1d3915e-52b6-4334-81bf-9a293e588309.png">
> 
> 모델 변환까지만 완료하고 이후 코드를 확인하지 않아 내용은 부족하지만 충분히 찾아보면 가능할 것 같습니다.
> 
> 그리고 위 에러는 저도 봤었는데 제가 스크립트로 따로 남겨놓지 않아서 정확히는 알려드릴 수 없지만 [edgetpu option](https://coral.ai/docs/edgetpu/compiler/#usage)을 확인하면 해결할 수 있을거라고 생각합니다.
> 
> ```
> Edge TPU Compiler version 16.0.384591198 Started a compilation timeout timer of 180 seconds. ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors. Compilation failed: Model failed in Tflite interpreter. Please ensure model can be loaded/run in Tflite interpreter. Compilation child process completed within timeout period. Compilation failed!
> ```
> 
> 열공하세요!

@ha4219  답장감사합니다😀
생각해보니 yolov5도 edgetpu모델로 변환후 돌아가는것을 보니 v7도 가능할것같다는 생각이 들긴하네요 시도해보고 후기남기겠습니다 : )

스타도 찍고갑니다~

**Comment by hi-one-gg** [comment]
@ha4219 바로 성공했습니다 ^^ 감사합니다ㅎㅎ

**Comment by hi-one-gg** [comment]
@ha4219 저.. 하나 더 여쭤보고싶은게 있는데,
yolov5든 yolov7든 edgetpu로 변환하고보니 아웃풋 shpae이 (1,6300, 85)인데 여기에 대한 post-processing이 안돼있더라구요..?

각 6300개의 객체에 대해서 85개의 정보가 있다는것으로 이해를 하고 있는데요~
혹시 이 85개의 정보를 어떻게 추출하면 될까요? (x,y,w,h... 이런 순으로 나가느거 같긴한데..)

**Comment by ha4219** [comment]
yolov5: https://github.com/ultralytics/yolov5/blob/454dae1301abb3fbf4fd1f54d5dc706cc69f8e7e/export.py#L508
yolov7:
https://github.com/WongKinYiu/yolov7/blob/8c0bf3f78947a2e81a1d552903b4934777acfa5f/export.py#L34

해당 부분은 nms 처리가 안돼서 그런 것 같은데 위에 링크 보시면 export할 때 nms 포함 여부를 선택할 수 있어요!! nms 포함해서 추출하시고 해보세요!!
@blackCmd
